services:
  API:
    image: simplebanking-api:1.0 # define o nome e versão da imagem
    build: . # cria a imagem a partir do dockerfile do diretorio
    ports: # mapeia as portas do host e do conatiner
      - "8080:8080"
    depends_on: # serviços que devem ser inicializados antes da web
      - DB
    networks:
      - public_network
      - private_network
    environment: # define as variaveis de ambiente do banco de dados
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  DB:
    image: postgres:17-alpine # CRIA UM CONTAINER A PARTIR DE UMA IMAGEM
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persiste os dados do postgres em um volume nomeado
    networks:
      - private_network
    environment: # define as variaveis de ambiente
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}


volumes:
  postgres_data: {} # volume para persistencia de dados do portgres

# define as redes que serão utilizadas
networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge