# Postgres configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/BankingSystem
spring.datasource.username=postgres
spring.datasource.password=1708
spring.jpa.hibernate.ddl-auto=update



# Profiles padrão
spring.profiles.active=dev
logging.level.org.springframework.security=TRACE

# swagger
springdoc.api;docs.path=/v3/api-docs
spring.swagger-ui.path=/swagger-ui.html


# Jpa generico
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Configurações de segurança
api.security.token.secret=secret
